- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: daemon-reload
  systemd:
    daemon_reload: yes